export const UPCOMING_CRUSADES = [
  { code: "AO", nation: "Angola", dates: "29 Aug", names: "Jesus Alive", types: "Mega Crusade", cities: "Luanda" },
  { code: "AR", nation: "Argentina", dates: "29 Aug", names: "Rhapsody Women Crusade", types: "Leading Ladies Crusade", cities: "Formosa" },
  { code: "BD", nation: "Bangladesh", dates: "29 Aug", names: "Joypurhut Community Crusade; Bollovpur Community Crusade; Khulna Community Crusade", types: "Mega Crusades", cities: "Rajshahi, Jessore, Khulna" },
  { code: "BB", nation: "Barbados", dates: "22 Aug", names: "NOTC", types: "Mega Crusade", cities: "Bridgetown" },
  { code: "BJ", nation: "Benin", dates: "22 Aug", names: "Movie Crusade (2 crusades)", types: "Say Yes To Kids Crusades", cities: "Cotonou" },
  { code: "BR", nation: "Brazil", dates: "29 Aug", names: "Itamarac Miracle Crusade NOTC Brazil", types: "Mega Crusade", cities: "Itamaracá" },
  { code: "CO", nation: "Colombia", dates: "21 Aug, 23 Aug, 29 Aug & 4 Sep", names: "La Carrera por la Última Alma Perdida; La Carrera por la Última Alma; Light Up Bucaramanga; Light Up Cucuta", types: "Mega Crusades", cities: "Sucre, Córdoba, Bucaramanga, Cúcuta" },
  { code: "CG", nation: "Congo - Brazzaville", dates: "7 Aug, 13 Aug, 28 Aug & 29 Aug", names: "Market Crusade; Brazzaville City Bus Station Crusades; Makelekele City Wide Crusade; Hospital Crusade", types: "Other; Transport Station; Mega; Hospital Crusade", cities: "Pointe-Noire, Brazzaville" },
  { code: "CR", nation: "Costa Rica", dates: "28 Aug", names: "Light Up Costa Rica", types: "Mega Crusade", cities: "San Jose" },
  { code: "CI", nation: "Côte d'Ivoire", dates: "22 Aug & 23 Aug", names: "Movie Crusade; Jesus Alive Crusade", types: "Say Yes To Kids; Mega Crusade", cities: "Abidjan, Koni" },
  { code: "GQ", nation: "Equatorial Guinea", dates: "29 Aug", names: "Night of A Thousand Crusades - Malabo", types: "Mega Crusade", cities: "Malabo" },
  { code: "FJ", nation: "Fiji", dates: "29 Aug & 5 Sep", names: "Rugby Crusade; Teaching Crusade; Rugby Nadi Crusade", types: "Other; Community Crusade", cities: "Sigatoka, Nadi" },
  { code: "GH", nation: "Ghana", dates: "22 Aug", names: "Movie Crusades (4); Movie Outreach", types: "Say Yes To Kids Crusades", cities: "Accra" },
  { code: "GT", nation: "Guatemala", dates: "25 Aug", names: "Light Up Guatemala", types: "Not specified", cities: "San Juan Sacatepequez" },
  { code: "GY", nation: "Guyana", dates: "29 Aug", names: "Jesus Alive Guyana", types: "Mega Crusade", cities: "Linden" },
  { code: "HN", nation: "Honduras", dates: "13 Aug & 29 Aug", names: "Ministers Teaching Crusade; Rhapsody Crusade Honduras", types: "Mega Crusades", cities: "Santa Rosa de Copan, San Pedro Sula" },
  { code: "IN", nation: "India", dates: "22 Aug & 23 Aug", names: "Movie Crusades (2); India Crusade", types: "Say Yes To Kids; Mega Crusade", cities: "Delhi, Chennai" },
  { code: "KE", nation: "Kenya", dates: "12 Aug, 21 Aug, 23 Aug, 27 Aug, 28 Aug, 30 Aug, 4 Sep & 6 Sep", names: "Kakamega County; Youth Aglow Crusade; Kisii University; Rongo University; Kodiaga Prison Crusade; Kitale Prison Crusade; Kisumu Prophetic Crusade; Tom Mboya University; Great Lakes University; Jaramogi Oginga Odinga University", types: "Street; Youths Aglow; Prison; Mega Crusades", cities: "Kakamega, Kisumu, Kisii, Rongo, Kitale, Homa Bay Town, Bondo" },
  { code: "LR", nation: "Liberia", dates: "28 Aug", names: "Say Yes To Kids Crusades", types: "Say Yes To Kids Crusades", cities: "Monrovia" },
  { code: "MU", nation: "Mauritius", dates: "29 Aug", names: "Night of A Thousand Crusades - Mauritius", types: "No One Left Behind Crusade", cities: "Mahebourg" },
  { code: "MZ", nation: "Mozambique", dates: "28 Aug, 29 Aug & 10 Oct", names: "Say Yes To Kids Crusades; Hospital Crusades; School Crusades; Night of A Thousand Crusades - Mozambique; Jesus Is Alive Mega Crusade", types: "Say Yes To Kids; School; Mega Crusades", cities: "Maputo, Chimoio" },
  { code: "NI", nation: "Nicaragua", dates: "29 Aug", names: "Ministers Teaching Crusade", types: "Mega Crusade", cities: "Managua" },
  { code: "NG", nation: "Nigeria", dates: "22 Aug, 26 Aug & 25 Sep", names: "Teens Ablaze Ibesikpo; Pad and Purpose Girls Crusade; Teens Arise Phase 2", types: "Teevolution; Mega Crusades", cities: "Uyo" },
  { code: "PK", nation: "Pakistan", dates: "23 Aug & 29 Aug", names: "Pakistan Crusades; Jesus Today and Forever; Evangelistic & Healing Crusade; Healing & Salvation; Healing & Deliverance; Winning Souls Crusades", types: "Mega, Village, Street & Football Stadium Crusades", cities: "Multiple Cities" },
  { code: "PG", nation: "Papua New Guinea", dates: "15 Aug, 20 Aug, 23 Aug, 29 Aug, 31 Aug & 5 Sep", names: "Mile Community; Gaire Village Crusade; Tubusereia Village; Papua New Guinea Mega Crusade 1; Boroka; Mega Crusade", types: "Community; Village; Mega; Other", cities: "Port Moresby" },
  { code: "PY", nation: "Paraguay", dates: "23 Aug, 29 Aug & 30 Aug", names: "Rhapsody Crusade; Rhapsody Military Crusade; Rhapsody Prison Crusades; Rhapsody Crusade Encarnacion", types: "Mega & Prison Crusades", cities: "Lambaré, Ypané, Asunción, Encarnacion" },
  { code: "WS", nation: "Samoa", dates: "29 Aug", names: "Teaching Crusade", types: "Community Crusade", cities: "Apia" },
  { code: "ZA", nation: "South Africa", dates: "22 Aug & 26 Aug", names: "Movie Outreach (Johannesburg & Cape Town); Youths Aglow SA", types: "Say Yes To Kids; Youths Aglow Crusades", cities: "Johannesburg, Cape Town" },
  { code: "SS", nation: "South Sudan", dates: "29 Aug", names: "Juba Miracle Crusade", types: "Mega Crusade", cities: "Juba" },
  { code: "TZ", nation: "Tanzania", dates: "26-31 Aug, 28 Aug & 29 Aug", names: "Teaching Program for Ministers; Dodoma Crusade; Dodoma Street Crusade", types: "Teaching & Street Crusades", cities: "Multiple Cities, Dodoma" },
  { code: "TG", nation: "Togo", dates: "28 Aug", names: "Marché Agoé Assiyéyé Market Crusade", types: "RABAH Crusade", cities: "Lomé" },
  { code: "VE", nation: "Venezuela", dates: "29 Aug", names: "NOTC - Maximum Impact Zulia City; Cultured By The Word", types: "Mega Crusades", cities: "Zulia City, Barquisimeto" },
].map((item) => ({ ...item, year: 2026 }));

export const upcomingCrusadeByCode = new Map(UPCOMING_CRUSADES.map((item) => [item.code, item]));
