import * as React from "react";
import { ChevronDown, Download, FileSpreadsheet, FileText, Paperclip, Search, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Breadcrumbs } from "@/components/ui/breadcrumbs";
import { Button } from "@/components/ui/button";
import { Field } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { deleteJSON, getJSON } from "@/lib/api";
import { nfull } from "@/lib/dashboardWidgets";

const espees = new Intl.NumberFormat("en", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const ES = (value) => `E ${espees.format(Number(value) || 0)}`;
const local = (value, code) => `${code} ${espees.format(Number(value) || 0)}`;

function CrusadeRows({ title, crusades, part }) {
  if (!crusades.length) return null;
  return <div className="mt-4 first:mt-0"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">{title}</p>
    <ul className="mt-2 space-y-3">{crusades.map((c) => <li key={c.id} className="border-t border-slate-200 pt-3">
      <div className="flex flex-wrap items-baseline justify-between gap-x-6 gap-y-1"><p className="font-semibold">{c.crusade_name} <span className="font-normal text-slate-500">· {[c.city, c.nation].filter(Boolean).join(", ")} · {c.event_date} · {nfull.format(c.attendance)} attendance</span></p><p className="tabular-nums"><span className="text-slate-500">{local(c.local_total, c.currency_code)}</span> <span className="ml-2 font-semibold">{ES(c.espees_equivalent)}</span></p></div>
      <p className="mt-1 text-xs text-slate-600">{part === "sponsored"
        ? [`Pastor's flight ${local(c.pastor_flight, c.currency_code)}`, c.accompanying_count ? `${c.accompanying_count} accompanying · ${local(c.accompanying_flight, c.currency_code)}` : null, `Sponsorship given ${local(c.sponsorship_given, c.currency_code)}`, c.other_cost_amount ? `Other ${local(c.other_cost_amount, c.currency_code)}${c.other_cost_note ? ` (${c.other_cost_note})` : ""}` : null, c.espees_already_given ? `Already given ${ES(c.espees_already_given)}` : null].filter(Boolean).join(" · ")
        : [`Venue ${local(c.venue_cost, c.currency_code)}`, `Transport ${local(c.transport_cost, c.currency_code)}`].join(" · ")}</p>
      {c.note && <p className="mt-1 text-xs text-slate-600">{c.note}</p>}
      {c.evidence.length > 0 ? <ul className="mt-2 flex flex-wrap gap-2">{c.evidence.map((file) => <li key={file.id}><a href={file.url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-3 py-1 text-xs hover:bg-slate-200"><FileText className="size-3 text-slate-500" />{file.original_name}</a></li>)}</ul>
        : <p className="mt-2 inline-flex items-center gap-1.5 text-xs text-amber-700"><Paperclip className="size-3" />No evidence uploaded</p>}
    </li>)}</ul></div>;
}

export function CrusadeExpensesAdmin() {
  const [data, setData] = React.useState(null); const [query, setQuery] = React.useState(""); const [zone, setZone] = React.useState(""); const [region, setRegion] = React.useState(""); const [sort, setSort] = React.useState("updated_at:desc"); const [open, setOpen] = React.useState(null);
  const params = React.useMemo(() => { const p = new URLSearchParams(); if (query.trim()) p.set("q", query.trim()); if (zone) p.set("zone", zone); if (region) p.set("region", region); const [field, direction] = sort.split(":"); p.set("sort", field); p.set("direction", direction); return p; }, [query, zone, region, sort]);
  const load = React.useCallback(() => getJSON(`/crusade-expenses/admin?${params}`).then(setData).catch((e) => toast.error(e.message)), [params]);
  React.useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [load]);
  async function remove(row) { if (!window.confirm(`Remove the expense report for ${row.zone_name}? Its uploaded evidence is deleted too.`)) return; try { await deleteJSON(`/crusade-expenses/admin/${row.id}`); await load(); toast.success("Expense report removed."); } catch (e) { toast.error(e.message); } }
  function exportRows(format) { const p = new URLSearchParams(params); p.set("format", format); window.location.assign(`/api/crusade-expenses/admin/export?${p}`); }
  const options = data?.filter_options || { zones: [], regions: [] }; const summary = data?.summary;

  return <div className="mx-auto max-w-7xl"><Breadcrumbs items={[{ label: "Reports dashboard", to: "/dashboard" }, { label: "Crusade expenses" }]} /><header className="flex flex-col gap-5 pb-10 pt-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-blue-700">Zonal crusade expense reports</p><h2 className="mt-2 text-4xl font-normal tracking-[-0.035em] text-slate-950">Crusade expenses</h2><p className="mt-3 text-sm text-slate-600">Part A is what zones spent on the crusades they were invited to. Part B is the mega crusades they planned and held themselves. Amounts are the Espees equivalents each zone supplied.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" className="rounded-full" onClick={() => exportRows("csv")} disabled={!data?.filtered_total}><Download /> CSV</Button><Button variant="outline" className="rounded-full" onClick={() => exportRows("xlsx")} disabled={!data?.filtered_total}><FileSpreadsheet /> Excel</Button></div></header>
    <section className="grid gap-px border-y border-slate-200 bg-slate-200 sm:grid-cols-2 xl:grid-cols-5">{[["Reports", summary ? nfull.format(summary.reports) : "—", "zones reporting"], ["Mega crusades", summary ? nfull.format(summary.crusades) : "—", "across both parts"], ["Part A — invited", summary ? ES(summary.sponsored_espees) : "—", "Espees equivalent"], ["Part B — their own crusades", summary ? ES(summary.own_espees) : "—", "Espees equivalent"], ["Already given", summary ? ES(summary.espees_already_given) : "—", "toward sponsorship"]].map(([label, value, sub]) => <div key={label} className="bg-white px-5 py-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">{label}</p><p className="mt-2 text-2xl font-medium tabular-nums tracking-[-0.02em]">{value}</p><p className="mt-1 text-xs text-slate-500">{sub}</p></div>)}</section>
    <section className="border-b border-slate-200 py-6"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-[1.3fr_repeat(3,auto)] xl:items-end"><Field label="Search"><div className="relative"><Search className="absolute left-0 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><Input value={query} onChange={(e) => setQuery(e.target.value)} className="pl-7" placeholder="Zone, pastor, KingsChat or reference" /></div></Field><Filter label="Region" value={region} set={setRegion} options={options.regions.map((v) => [v, v])} all="All regions" /><Filter label="Zone" value={zone} set={setZone} options={options.zones.map((v) => [v, v])} all="All zones" /><Field label="Sort"><Select value={sort} onChange={(e) => setSort(e.target.value)}><option value="updated_at:desc">Recently updated</option><option value="total:desc">Highest total</option><option value="total:asc">Lowest total</option><option value="crusades:desc">Most crusades</option><option value="zone:asc">Zone A–Z</option></Select></Field></div></section>
    <div className="flex gap-7 py-6 text-sm"><p><strong className="text-2xl font-medium">{data?.total ?? "—"}</strong><span className="ml-2 text-slate-500">reports</span></p><p className="self-center text-slate-500">{data?.filtered_total ?? 0} shown</p></div>
    <div className="border-y border-slate-200">{!data ? <Skeleton className="h-40 rounded-none" /> : data.rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead><tr className="text-left text-xs text-slate-500"><th className="px-3 py-3">Zone</th><th className="px-3 py-3">Pastor</th><th className="px-3 py-3">Crusades</th><th className="px-3 py-3 text-right">Part A</th><th className="px-3 py-3 text-right">Part B</th><th className="px-3 py-3 text-right">Total</th><th className="px-3 py-3">Updated</th><th className="px-3 py-3">Action</th></tr></thead><tbody>{data.rows.map((row) => { const expanded = open === row.id; return <React.Fragment key={row.id}>
      <tr className="border-t border-slate-200 align-top"><td className="px-3 py-4"><button type="button" onClick={() => setOpen(expanded ? null : row.id)} aria-expanded={expanded} className="flex items-start gap-2 text-left font-semibold"><ChevronDown className={`mt-0.5 size-4 shrink-0 text-slate-400 transition-transform duration-200 ${expanded ? "rotate-180" : ""}`} /><span>{row.zone_name}<span className="mt-1 block text-xs font-normal text-slate-500">{row.region || "Region not mapped"} · {row.reference_code}</span></span></button></td>
        <td className="px-3 py-4"><p>{row.designation} {row.first_name} {row.last_name}</p><p className="mt-1 text-xs text-slate-500">@{row.kingschat_username}</p></td>
        <td className="px-3 py-4"><p>{nfull.format(row.crusade_count)}</p><p className="mt-1 text-xs text-slate-500">A {row.sponsored.length} · B {row.own.length}</p></td>
        <td className="px-3 py-4 text-right tabular-nums">{ES(row.sponsored_espees)}</td><td className="px-3 py-4 text-right tabular-nums">{ES(row.own_espees)}</td><td className="px-3 py-4 text-right font-semibold tabular-nums">{ES(row.total_espees)}</td>
        <td className="whitespace-nowrap px-3 py-4 text-xs text-slate-500">{row.updated_at}</td>
        <td className="px-3 py-4"><Button variant="ghost" size="sm" className="text-slate-600 hover:text-red-700" onClick={() => remove(row)}><Trash2 /> Remove</Button></td></tr>
      {expanded && <tr className="bg-slate-50"><td colSpan={8} className="px-3 pb-6 pt-1"><div className="max-w-4xl"><CrusadeRows title="Part A — crusades they were invited to" crusades={row.sponsored} part="sponsored" /><CrusadeRows title="Part B — crusades they planned and held" crusades={row.own} part="own" />{row.notes && <p className="mt-4 border-l-2 border-amber-500 pl-4 text-sm leading-6 text-slate-700"><span className="font-semibold">Notes:</span> {row.notes}</p>}<p className="mt-3 text-xs text-slate-500">Submitted {row.created_at}</p></div></td></tr>}
    </React.Fragment>; })}</tbody></table></div> : <div className="py-16 text-center"><p className="font-semibold">No expense reports yet</p><p className="mt-2 text-sm text-slate-500">Zonal pastors submit them at /crusade-expenses.</p></div>}</div></div>;
}
function Filter({ label, value, set, options, all }) { return <Field label={label}><Select value={value} onChange={(e) => set(e.target.value)}><option value="">{all}</option>{options.map(([v, l]) => <option key={v} value={v}>{l}</option>)}</Select></Field>; }
