import * as React from "react";
import { Download, FileSpreadsheet, Search, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Breadcrumbs } from "@/components/ui/breadcrumbs";
import { Button } from "@/components/ui/button";
import { Field } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { deleteJSON, getJSON } from "@/lib/api";

export function MissionTripAdmin() {
  const [data, setData] = React.useState(null); const [query, setQuery] = React.useState(""); const [zone, setZone] = React.useState(""); const [passport, setPassport] = React.useState(""); const [destination, setDestination] = React.useState(""); const [sort, setSort] = React.useState("created_at:desc");
  const params = React.useMemo(() => { const p = new URLSearchParams(); if (query.trim()) p.set("q", query.trim()); if (zone) p.set("zone", zone); if (passport) p.set("passport", passport); if (destination) p.set("destination", destination); const [field, direction] = sort.split(":"); p.set("sort", field); p.set("direction", direction); return p; }, [query, zone, passport, destination, sort]);
  const load = React.useCallback(() => getJSON(`/mission-trips/admin?${params}`).then(setData).catch(e => toast.error(e.message)), [params]); React.useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [load]);
  async function remove(row) { if (!window.confirm(`Remove ${row.first_name} ${row.last_name}'s volunteer application?`)) return; try { await deleteJSON(`/mission-trips/admin/${row.id}`); await load(); toast.success("Application removed."); } catch (e) { toast.error(e.message); } }
  function exportRows(format) { const p = new URLSearchParams(params); p.set("format", format); window.location.assign(`/api/mission-trips/admin/export?${p}`); }
  const options = data?.filter_options || { zones: [], passports: [], destinations: [] };
  return <div className="mx-auto max-w-7xl"><Breadcrumbs items={[{ label: "Reports dashboard", to: "/dashboard" }, { label: "Mission-trip volunteers" }]} /><header className="flex flex-col gap-5 pb-10 pt-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-blue-700">NOTC Global Missions Trip Volunteer Mobilisation</p><h2 className="mt-2 text-4xl font-normal tracking-[-0.035em] text-slate-950">Volunteer applications</h2><p className="mt-3 text-sm text-slate-600">Review travel-ready members by passport, accessible nation, and ministry location.</p></div><div className="flex gap-2"><Button variant="outline" className="rounded-full" onClick={() => exportRows("csv")} disabled={!data?.filtered_total}><Download /> CSV</Button><Button variant="outline" className="rounded-full" onClick={() => exportRows("xlsx")} disabled={!data?.filtered_total}><FileSpreadsheet /> Excel</Button></div></header>
    <section className="border-y border-slate-200 py-6"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-[1.3fr_repeat(4,auto)] xl:items-end"><Field label="Search"><div className="relative"><Search className="absolute left-0 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><Input value={query} onChange={e => setQuery(e.target.value)} className="pl-7" placeholder="Name, email, KingsChat or zone" /></div></Field><Filter label="Zone" value={zone} set={setZone} options={options.zones.map(v => [v,v])} all="All zones" /><Filter label="Passport" value={passport} set={setPassport} options={options.passports.map(v => [v.code,v.name])} all="All passports" /><Filter label="Destination" value={destination} set={setDestination} options={options.destinations.map(v => [v.code,v.name])} all="All destinations" /><Field label="Sort"><Select value={sort} onChange={e => setSort(e.target.value)}><option value="created_at:desc">Newest first</option><option value="created_at:asc">Oldest first</option><option value="name:asc">Name A–Z</option><option value="passport:asc">Passport A–Z</option><option value="destination:asc">Destination A–Z</option></Select></Field></div></section>
    <div className="flex gap-7 py-6 text-sm"><p><strong className="text-2xl font-medium">{data?.total ?? "—"}</strong><span className="ml-2 text-slate-500">applications</span></p><p className="self-center text-slate-500">{data?.filtered_total ?? 0} shown</p></div>
    <div className="border-y border-slate-200">{!data ? <Skeleton className="h-40 rounded-none" /> : data.rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead><tr className="text-left text-xs text-slate-500"><th className="px-3 py-3">Volunteer</th><th className="px-3 py-3">Passport</th><th className="px-3 py-3">Mission interest</th><th className="px-3 py-3">Ministry</th><th className="px-3 py-3">Contact</th><th className="px-3 py-3">Submitted</th><th className="px-3 py-3">Action</th></tr></thead><tbody>{data.rows.map(row => <tr key={row.id} className="border-t border-slate-200 align-top"><td className="px-3 py-4"><p className="font-semibold">{row.first_name} {row.last_name}</p><p className="mt-1 text-xs text-slate-500">{row.designation} · {row.reference_code}</p></td><td className="px-3 py-4"><p>{row.passport_country_name}</p><p className="mt-1 text-xs text-slate-500">Expires {row.passport_expiry}{row.additional_passports ? ` · +${row.additional_passports.split(",").length} more` : ""}</p></td><td className="px-3 py-4"><p>{row.preferred_destination_name}</p><p className="mt-1 text-xs text-slate-500">{row.ready_for_any_destination ? "Open to reassignment" : "Preferred only"}{row.sponsor_interest ? " · Sponsor interest" : ""}</p></td><td className="px-3 py-4"><p>{row.zone_name || "—"}</p><p className="mt-1 text-xs text-slate-500">{[row.group_name,row.church_name].filter(Boolean).join(" · ") || "No group/church"}</p></td><td className="px-3 py-4"><p>{row.email}</p><p className="mt-1 text-xs text-slate-500">@{row.kingschat_username} · {row.phone_country_code} {row.phone_number}</p></td><td className="whitespace-nowrap px-3 py-4 text-xs text-slate-500">{row.created_at}</td><td className="px-3 py-4"><Button variant="ghost" size="sm" className="text-slate-600 hover:text-red-700" onClick={() => remove(row)}><Trash2 /> Remove</Button></td></tr>)}</tbody></table></div> : <div className="py-16 text-center"><p className="font-semibold">No applications found</p><p className="mt-2 text-sm text-slate-500">Change the active filters or wait for new volunteer applications.</p></div>}</div></div>;
}
function Filter({ label, value, set, options, all }) { return <Field label={label}><Select value={value} onChange={e => set(e.target.value)}><option value="">{all}</option>{options.map(([v,l]) => <option key={v} value={v}>{l}</option>)}</Select></Field>; }
