/* THESIS: A composed international-service application, not a generic event form. OWN-WORLD: campaign navy, paper white, partnership gold. STORY: eligibility → ministry context → readiness → commitment. */
import * as React from "react";
import { Link } from "react-router-dom";
import { Controller, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Check, Globe2, HeartHandshake, Plane, Plus, ShieldCheck, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Field } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Combobox } from "@/components/Combobox";
import { getJSON, postJSON } from "@/lib/api";
import { PHONE_CODES } from "@/lib/constants";
import { missionTripVolunteerSchema } from "@/lib/schema";
import { useOrgData } from "@/lib/orgForm";

const defaults = { designation: "", first_name: "", last_name: "", email: "", phone_country_code: "", phone_number: "", kingschat_username: "", zone_name: "", group_name: "", church_name: "", passport_country_code: "", additional_passports: [], passport_expiry: "", preferred_destination_code: "", ready_for_any_destination: false, valid_passport: false, covers_travel_expenses: false, medically_fit: false, sponsor_interest: false, partnership_acknowledged: false, additional_information: "" };
const Checkbox = ({ id, children, error, ...props }) => <div><label htmlFor={id} className="flex cursor-pointer items-start gap-3 text-sm leading-6 text-slate-700"><input id={id} type="checkbox" className="mt-1 size-4 accent-slate-950" {...props} /><span>{children}</span></label>{error && <p className="ml-7 mt-1 text-xs font-medium text-red-700">{error}</p>}</div>;

function Confirmation({ result }) {
  return <div className="min-h-screen bg-[#f6f2e8]"><header className="border-b border-black/10 bg-white"><div className="mx-auto flex max-w-6xl items-center px-5 py-4"><img src="/logo.png" alt="" className="h-11" /><Link to="/" className="ml-auto text-sm font-semibold">Return home</Link></div></header><main className="mx-auto max-w-3xl px-5 py-20"><span className="grid size-14 place-items-center rounded-full bg-[#18234d] text-white"><Check /></span><p className="mt-8 text-sm font-semibold text-amber-700">Application received</p><h1 className="mt-3 text-5xl font-medium leading-none tracking-[-0.04em] text-slate-950">Thank you for answering the call.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{result.full_name}, the missions team will review your travel readiness and contact you about suitable opportunities.</p><dl className="mt-12 border-y border-black/15">{[["Passport", result.passport_country_name], ["Preferred destination", result.preferred_destination_name], ["Reference", result.reference_code]].map(([label,value]) => <div key={label} className="grid border-b border-black/10 py-4 last:border-0 sm:grid-cols-[12rem_1fr]"><dt className="text-sm text-slate-500">{label}</dt><dd className="font-semibold">{value}</dd></div>)}</dl><p className="mt-8 border-l-2 border-amber-500 pl-5 text-sm leading-6 text-slate-700">Your approved, personally covered mission-trip expenses will be recorded as your Rhapsody of Realities partnership.</p>{result.sponsor_interest && <Button asChild className="mt-8 rounded-full bg-[#18234d] px-7 hover:bg-[#24346d]"><a href="https://rhapsodycrusades.org/sponsor">Sponsor a mission trip</a></Button>}</main></div>;
}

export function MissionTripRegistration() {
  const [result, setResult] = React.useState(null); const [countries, setCountries] = React.useState([]); const [extraPassport, setExtraPassport] = React.useState("");
  const { register, control, setValue, watch, handleSubmit, formState: { errors, isSubmitting } } = useForm({ resolver: zodResolver(missionTripVolunteerSchema), defaultValues: defaults, mode: "onBlur" });
  const zone = watch("zone_name"); const extras = watch("additional_passports"); const { fetchZones, fetchGroups, clearGroupCache } = useOrgData(zone);
  React.useEffect(() => { getJSON("/countries").then(setCountries).catch(() => toast.error("Could not load the country list.")); }, []);
  async function submit(data) { try { setResult(await postJSON("/mission-trips/registrations", data)); window.scrollTo({ top: 0 }); } catch (error) { toast.error(error.message); } }
  function addPassport() { if (extraPassport && !extras.includes(extraPassport) && extras.length < 5) setValue("additional_passports", [...extras, extraPassport], { shouldValidate: true }); setExtraPassport(""); }
  if (result) return <Confirmation result={result} />;
  const countryOptions = countries.map((item) => <option key={item.code} value={item.code}>{item.name}</option>);
  return <div className="min-h-screen bg-[#f6f2e8] text-slate-950"><header className="border-b border-black/10 bg-white"><div className="mx-auto flex max-w-7xl items-center gap-3 px-5 py-4"><Link to="/"><img src="/logo.png" alt="A Night of a Thousand Crusades" className="h-11" /></Link><span className="hidden min-w-0 truncate text-sm font-semibold sm:block">Global Missions Trip Volunteer Mobilisation</span><Link to="/" className="ml-auto shrink-0 text-sm font-semibold">Return home</Link></div></header>
    <main className="mx-auto grid max-w-7xl lg:grid-cols-[24rem_minmax(0,1fr)]"><aside className="bg-[#18234d] text-white lg:sticky lg:top-0 lg:min-h-[calc(100vh-77px)] lg:self-start"><h1 className="sr-only">NIGHT OF A THOUSAND CRUSADES (NOTC) GLOBAL MISSIONS TRIP VOLUNTEER MOBILISATION</h1><img src="/global-missions-trip-volunteer.png" alt="Night of a Thousand Crusades Global Missions Trip Volunteer Mobilisation" className="aspect-square w-full bg-white object-contain" /><div className="space-y-5 px-6 py-8 sm:px-10"><p className="leading-7 text-slate-300">Make yourself available to serve in a nation you can enter independently.</p><div className="space-y-5 border-t border-white/20 pt-7"><p className="flex gap-3 text-sm leading-6 text-slate-300"><Plane className="mt-0.5 size-5 shrink-0 text-amber-300" /><span>Visa and travel permissions cannot be facilitated for volunteers. Only indicate nations you can access independently.</span></p><p className="flex gap-3 text-sm leading-6 text-slate-300"><HeartHandshake className="mt-0.5 size-5 shrink-0 text-amber-300" /><span>Your approved personal expenses will count as Rhapsody of Realities partnership.</span></p></div></div></aside>
    <form onSubmit={handleSubmit(submit, () => toast.error("Check the highlighted application details."))} className="bg-white px-5 py-12 sm:px-10 lg:px-14 lg:py-16"><div className="max-w-3xl"><p className="text-sm font-semibold text-amber-700">Volunteer application</p><h2 className="mt-3 text-3xl font-medium leading-tight tracking-[-0.035em] sm:text-4xl">NIGHT OF A THOUSAND CRUSADES (NOTC) GLOBAL MISSIONS TRIP VOLUNTEER MOBILISATION</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600">We are mobilising volunteers from across our churches, zones, and networks to participate in missions trips and support the global outreach efforts.</p><p className="mt-5 max-w-2xl border-l-2 border-amber-500 pl-5 text-sm leading-6 text-slate-700">Use this form to share the nations you can access, your passport and visa access, availability, interests, and areas of service.</p>
      <Section icon={ShieldCheck} title="Personal information" copy="Use details the missions team can verify and reach directly."><Field label="Designation" required error={errors.designation?.message} className="sm:col-span-2"><Select {...register("designation")}><option value="">Select designation</option>{["Pastor","Deacon","Deaconess","Brother","Sister","Other"].map(v => <option key={v}>{v}</option>)}</Select></Field><Field label="First name" required error={errors.first_name?.message}><Input {...register("first_name")} /></Field><Field label="Last name" required error={errors.last_name?.message}><Input {...register("last_name")} /></Field><Field label="Email" required error={errors.email?.message}><Input type="email" {...register("email")} /></Field><Field label="KingsChat username" hint="Optional" error={errors.kingschat_username?.message}><Input {...register("kingschat_username")} placeholder="@username" /></Field><Field label="Phone number" required error={errors.phone_country_code?.message || errors.phone_number?.message} className="sm:col-span-2"><div className="flex gap-2"><Select className="w-28" {...register("phone_country_code")}><option value="">Code</option>{PHONE_CODES.map(v => <option key={v}>{v}</option>)}</Select><Input type="tel" {...register("phone_number")} /></div></Field></Section>
      <Section icon={Globe2} title="Church information" copy="Optional—complete only the level that applies to you."><Field label="Zone"><Controller control={control} name="zone_name" render={({field}) => <Combobox value={field.value} fetcher={fetchZones} onSelect={o => { field.onChange(o.value); setValue("group_name", ""); clearGroupCache(); }} placeholder="Select your zone, if applicable" caps />} /></Field><Field label="Group"><Controller control={control} name="group_name" render={({field}) => <Combobox value={field.value} fetcher={fetchGroups} onSelect={o => field.onChange(o.label)} disabled={!zone} placeholder={zone ? "Select group, if applicable" : "Select a zone first"} caps />} /></Field><Field label="Church" className="sm:col-span-2"><Input {...register("church_name")} placeholder="Enter your church name, if applicable" /></Field></Section>
      <Section icon={Plane} title="Passport and mission interest" copy="Tell us which passport or passports you hold. Do not enter a passport number."><Field label="Primary passport" required error={errors.passport_country_code?.message}><Select {...register("passport_country_code")}><option value="">Select passport country</option>{countryOptions}</Select></Field><Field label="Passport expiry" required error={errors.passport_expiry?.message}><Input type="month" min={new Date().toISOString().slice(0,7)} {...register("passport_expiry")} /></Field><Field label="Additional passports" hint="Optional—up to five" className="sm:col-span-2"><div className="flex gap-2"><Select value={extraPassport} onChange={e => setExtraPassport(e.target.value)}><option value="">Select another passport</option>{countries.filter(c => !extras.includes(c.code)).map(c => <option key={c.code} value={c.code}>{c.name}</option>)}</Select><Button type="button" variant="outline" size="icon" onClick={addPassport} aria-label="Add passport"><Plus /></Button></div>{extras.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{extras.map(code => <span key={code} className="inline-flex items-center gap-2 rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">{countries.find(c => c.code === code)?.name}<button type="button" onClick={() => setValue("additional_passports", extras.filter(v => v !== code))} aria-label="Remove passport"><X className="size-3" /></button></span>)}</div>}</Field><Field label="Nation you can access" required error={errors.preferred_destination_code?.message} className="sm:col-span-2"><Select {...register("preferred_destination_code")}><option value="">Select a nation you can enter independently</option>{countryOptions}</Select></Field><div className="sm:col-span-2"><Checkbox id="any-destination" {...register("ready_for_any_destination")}>I can independently access other destinations and am open to being considered for them.</Checkbox></div></Section>
      <section className="mt-12 border-y border-black/15 py-9"><h3 className="text-2xl font-medium tracking-[-0.02em]">Travel readiness and partnership</h3><div className="mt-6 border-l-2 border-amber-500 bg-amber-50 px-5 py-4"><p className="font-semibold">Your expenses count as partnership.</p><p className="mt-1 text-sm leading-6 text-slate-700">Approved mission-trip expenses you personally cover will be recorded as your Rhapsody of Realities partnership.</p></div><div className="mt-7 space-y-4"><Checkbox id="valid-passport" error={errors.valid_passport?.message} {...register("valid_passport")}>I hold a valid passport and can provide proof when requested.</Checkbox><Checkbox id="travel-cost" error={errors.covers_travel_expenses?.message} {...register("covers_travel_expenses")}>I can enter my selected nation without visa support or special arrangements, and I will cover my approved travel expenses.</Checkbox><Checkbox id="medical" error={errors.medically_fit?.message} {...register("medically_fit")}>I am in good health and can obtain medical clearance for international travel.</Checkbox><Checkbox id="sponsor" {...register("sponsor_interest")}>I would also like to sponsor a mission trip.</Checkbox><Checkbox id="partnership" error={errors.partnership_acknowledged?.message} {...register("partnership_acknowledged")}>I understand that my approved, personally covered expenses will be recorded as my Rhapsody of Realities partnership.</Checkbox></div></section>
      <section className="py-10"><Field label="Additional information" hint="Share your availability, skills, areas of service, travel experience, languages, or relevant questions."><Textarea rows={5} {...register("additional_information")} /></Field><p className="mt-6 text-sm font-medium text-[#18234d]">One Mission. One Movement. 242 Nations Reached.</p><div className="mt-8 flex flex-col-reverse gap-4 border-t border-black/10 pt-8 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-md text-xs leading-5 text-slate-500">The missions team will review applications and contact suitable volunteers. Do not make travel bookings until your mission assignment is confirmed.</p><Button type="submit" disabled={isSubmitting} className="rounded-full bg-[#18234d] px-7 hover:bg-[#24346d]">{isSubmitting ? "Submitting application…" : "Submit volunteer application"}</Button></div></section>
    </div></form></main></div>;
}

function Section({ icon: Icon, title, copy, children }) { return <section className="mt-12"><div className="flex gap-3"><Icon className="mt-1 size-5 text-amber-600" /><div><h3 className="text-2xl font-medium tracking-[-0.02em]">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{copy}</p></div></div><div className="mt-6 grid gap-5 border-y border-black/15 py-8 sm:grid-cols-2">{children}</div></section>; }
