import * as React from "react";
import { Link } from "react-router-dom";
import { zodResolver } from "@hookform/resolvers/zod";
import { Controller, useForm } from "react-hook-form";
import { CalendarDays, Check, Globe2, MapPin, Plane, Search, ShieldCheck, UserRound } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Combobox } from "@/components/Combobox";
import { Field } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { getJSON, postJSON } from "@/lib/api";
import { PHONE_CODES } from "@/lib/constants";
import { useOrgData } from "@/lib/orgForm";
import { upcomingCrusadeInterestSchema } from "@/lib/schema";

const defaults = { full_name: "", zone_name: "", group_name: "", email: "", kingschat_username: "", phone_country_code: "", phone_number: "", passport_country_code: "", passport_expiry: "", opportunity_codes: [], valid_passport: false, destination_access: false, available_to_travel: false, additional_information: "" };

function Confirmation({ result }) {
  const nations = result.opportunities.map((item) => item.nation).join(" and ");
  return <div className="min-h-screen bg-slate-50"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-5xl items-center px-4 py-4 sm:px-6"><img src="/logo.png" alt="" className="h-11" /><Link to="/" className="ml-auto text-sm font-semibold">Return home</Link></div></header><main className="mx-auto max-w-3xl px-4 py-14 sm:px-6 sm:py-20"><span className="grid size-12 place-items-center rounded-full bg-emerald-700 text-white"><Check /></span><p className="mt-8 text-sm font-semibold text-blue-700">Interest received</p><h1 className="mt-3 text-4xl font-normal tracking-[-0.035em] sm:text-5xl">You selected {nations}.</h1><p className="mt-5 leading-7 text-slate-600">The missions department will review your travel eligibility and contact you. Do not make travel bookings until your participation is confirmed.</p><dl className="mt-10 border-y border-slate-200">{[["Reference", result.reference_code], ["Zone", result.zone_name], result.group_name && ["Group", result.group_name]].filter(Boolean).map(([label,value]) => <div key={label} className="grid gap-1 border-b border-slate-200 py-4 last:border-0 sm:grid-cols-[10rem_1fr]"><dt className="text-sm text-slate-500">{label}</dt><dd className="text-sm font-semibold">{value}</dd></div>)}{result.opportunities.map((item, index) => <div key={item.code} className="border-b border-slate-200 py-5 last:border-0"><dt className="text-xs font-semibold uppercase tracking-[0.08em] text-blue-700">Choice {index + 1}</dt><dd className="mt-2 font-semibold">{item.nation}</dd><dd className="mt-1 text-sm text-slate-600">{item.dates} · {item.cities}</dd><dd className="mt-1 text-sm text-slate-600">{item.names}</dd></div>)}</dl></main></div>;
}

function Checkbox({ id, error, children, ...props }) {
  return <div><label htmlFor={id} className="flex cursor-pointer items-start gap-3 text-sm leading-6 text-slate-700"><input id={id} type="checkbox" className="mt-1 size-4 shrink-0 accent-blue-700" {...props} /><span>{children}</span></label>{error && <p className="mt-1 pl-7 text-xs font-medium text-red-700">{error}</p>}</div>;
}

export function UpcomingCrusades() {
  const [catalogue, setCatalogue] = React.useState([]);
  const [countries, setCountries] = React.useState([]);
  const [query, setQuery] = React.useState("");
  const [result, setResult] = React.useState(null);
  const { register, control, setValue, watch, handleSubmit, formState: { errors, isSubmitting } } = useForm({ resolver: zodResolver(upcomingCrusadeInterestSchema), defaultValues: defaults, mode: "onBlur" });
  const zone = watch("zone_name");
  const selectedCodes = watch("opportunity_codes");
  const selected = selectedCodes.map((code) => catalogue.find((item) => item.code === code)).filter(Boolean);
  const { fetchZones, fetchGroups, clearGroupCache } = useOrgData(zone);

  React.useEffect(() => {
    Promise.all([getJSON("/upcoming-crusades"), getJSON("/countries")])
      .then(([opportunities, countryList]) => { setCatalogue(opportunities.opportunities); setCountries(countryList); })
      .catch((error) => toast.error(error.message));
  }, []);

  const shown = catalogue.filter((item) => `${item.nation} ${item.cities} ${item.names}`.toLowerCase().includes(query.trim().toLowerCase()));
  async function submit(data) {
    try { setResult(await postJSON("/upcoming-crusades/interests", data)); window.scrollTo({ top: 0, behavior: "smooth" }); }
    catch (error) { toast.error(error.message); }
  }
  function toggleOpportunity(code) {
    if (selectedCodes.includes(code)) return setValue("opportunity_codes", selectedCodes.filter((item) => item !== code), { shouldValidate: true, shouldDirty: true });
    if (selectedCodes.length >= 2) return toast.error("You can select up to two upcoming crusades.");
    setValue("opportunity_codes", [...selectedCodes, code], { shouldValidate: true, shouldDirty: true });
  }

  if (result) return <Confirmation result={result} />;
  return <div className="min-h-screen bg-[#f5f7fb] text-slate-950">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center gap-3 px-4 py-4 sm:px-6"><Link to="/"><img src="/logo.png" alt="A Night of a Thousand Crusades" className="h-11" /></Link><span className="hidden text-sm font-semibold sm:block">Upcoming Crusades</span><Link to="/" className="ml-auto text-sm font-semibold">Return home</Link></div></header>
    <main>
      <section className="bg-[#121944] text-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-12 sm:px-6 sm:py-16 lg:grid-cols-[1fr_24rem] lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.08em] text-blue-300">Nations & Continents Edition</p><h1 className="mt-4 max-w-4xl text-4xl font-normal leading-[1.02] tracking-[-0.04em] sm:text-6xl">Upcoming Crusade</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">We have crusades planned across nations and cities. As a zonal pastor, indicate up to two nations you would like to travel to.</p></div><div className="border border-white/15 bg-white/10 p-6"><ShieldCheck className="size-7 text-amber-300" /><h2 className="mt-5 text-xl font-medium">Travel access is required</h2><p className="mt-3 text-sm leading-6 text-slate-300">You must hold a valid passport and already possess the required visa or visa-free entry permission for the destination. Visa arrangements cannot be guaranteed by the department.</p></div></div></section>

      <form onSubmit={handleSubmit(submit, () => toast.error("Complete the highlighted details and select one crusade."))} className="mx-auto max-w-7xl px-4 py-10 sm:px-6 sm:py-14">
        <section className="grid gap-8 border-b border-slate-200 pb-12 lg:grid-cols-[18rem_minmax(0,1fr)] lg:gap-14"><div><p className="text-sm font-semibold text-blue-700">Zonal pastor details</p><h2 className="mt-3 text-2xl font-medium">Provide your contact details.</h2><p className="mt-3 text-sm leading-6 text-slate-600">Select the zone you pastor. You may also include a group, but it is optional.</p></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Full name" required error={errors.full_name?.message}><Input {...register("full_name")} aria-invalid={Boolean(errors.full_name)} /></Field><Field label="KingsChat username" required error={errors.kingschat_username?.message}><Input {...register("kingschat_username")} placeholder="@username" aria-invalid={Boolean(errors.kingschat_username)} /></Field><Field label="Zone" required error={errors.zone_name?.message}><Controller control={control} name="zone_name" render={({ field }) => <Combobox value={field.value} fetcher={fetchZones} onSelect={(option) => { field.onChange(option.value); setValue("group_name", ""); clearGroupCache(); }} placeholder="Select your zone" searchPlaceholder="Search zones…" invalid={Boolean(errors.zone_name)} caps />} /></Field><Field label="Group" hint="Optional" error={errors.group_name?.message}><Controller control={control} name="group_name" render={({ field }) => <Combobox value={field.value} fetcher={fetchGroups} onSelect={(option) => field.onChange(option.label)} disabled={!zone} placeholder={zone ? "Select group, if applicable" : "Select a zone first"} searchPlaceholder="Search groups…" invalid={Boolean(errors.group_name)} caps />} /></Field><Field label="Email" required error={errors.email?.message}><Input type="email" {...register("email")} aria-invalid={Boolean(errors.email)} /></Field><Field label="Phone number" required error={errors.phone_country_code?.message || errors.phone_number?.message}><div className="flex gap-2"><Select className="w-28 shrink-0" {...register("phone_country_code")} aria-invalid={Boolean(errors.phone_country_code)}><option value="">Code</option>{PHONE_CODES.map((code) => <option key={code}>{code}</option>)}</Select><Input type="tel" {...register("phone_number")} aria-invalid={Boolean(errors.phone_number)} /></div></Field></div></section>

        <section className="grid gap-8 border-b border-slate-200 py-12 lg:grid-cols-[18rem_minmax(0,1fr)] lg:gap-14"><div><p className="text-sm font-semibold text-blue-700">Travel eligibility</p><h2 className="mt-3 text-2xl font-medium">Confirm access before choosing.</h2><p className="mt-3 text-sm leading-6 text-slate-600">Do not submit for a nation you cannot legally enter.</p></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Passport country" required error={errors.passport_country_code?.message}><Select {...register("passport_country_code")} aria-invalid={Boolean(errors.passport_country_code)}><option value="">Select passport country</option>{countries.map((country) => <option key={country.code} value={country.code}>{country.name}</option>)}</Select></Field><Field label="Passport expiry" required error={errors.passport_expiry?.message}><Input type="month" min={new Date().toISOString().slice(0,7)} {...register("passport_expiry")} aria-invalid={Boolean(errors.passport_expiry)} /></Field><div className="space-y-4 sm:col-span-2"><Checkbox id="upcoming-valid-passport" error={errors.valid_passport?.message} {...register("valid_passport")}>I hold a valid passport and can provide proof when requested.</Checkbox><Checkbox id="upcoming-destination-access" error={errors.destination_access?.message} {...register("destination_access")}>I already have the required visa, or I have confirmed visa-free/visa-on-arrival access, for the destination I select.</Checkbox><Checkbox id="upcoming-travel-ready" error={errors.available_to_travel?.message} {...register("available_to_travel")}>I am available to travel for the published crusade dates and understand that final participation must be confirmed by the department.</Checkbox></div></div></section>

        <section className="py-12"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold text-blue-700">Published schedule</p><h2 className="mt-3 text-3xl font-normal tracking-[-0.03em]">Select up to two upcoming crusades.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Choose only destinations you can enter independently. Your selections will be highlighted before submission.</p></div><div className="relative w-full max-w-sm"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><Input value={query} onChange={(event) => setQuery(event.target.value)} className="pl-9" placeholder="Search nation, city or crusade" /></div></div>
          <div className={`mt-6 flex items-center gap-3 border px-4 py-3 text-sm ${errors.opportunity_codes ? "border-red-300 bg-red-50 text-red-800" : selected.length ? "border-emerald-300 bg-emerald-50 text-emerald-900" : "border-blue-200 bg-blue-50 text-blue-900"}`} role="status" aria-live="polite"><span className={`grid size-7 shrink-0 place-items-center rounded-full text-white ${selected.length ? "bg-emerald-700" : "bg-blue-700"}`}>{selected.length ? <Check className="size-4" /> : <Globe2 className="size-4" />}</span><span className="font-medium">{errors.opportunity_codes ? errors.opportunity_codes.message : selected.length ? `${selected.map((item) => item.nation).join(" and ")} selected · ${selected.length} of 2.` : "Tap one or two destinations below to select them."}</span></div>
          <div className="mt-6 grid gap-3 md:grid-cols-2">{shown.map((item) => { const active = selectedCodes.includes(item.code); return <button key={item.code} type="button" aria-pressed={active} onClick={() => toggleOpportunity(item.code)} className={`group min-w-0 border p-5 text-left transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 ${active ? "border-slate-950 bg-slate-950 text-white shadow-lg" : "border-slate-200 bg-white hover:border-blue-400 hover:shadow-md"}`}><div className="flex items-start justify-between gap-4"><div><p className={`text-xs font-semibold uppercase tracking-[0.08em] ${active ? "text-blue-300" : "text-blue-700"}`}>{item.code} · {item.types}</p><h3 className="mt-2 text-xl font-medium">{item.nation}</h3></div><span className={`grid size-7 shrink-0 place-items-center rounded-full border ${active ? "border-white bg-white text-slate-950" : "border-slate-300 text-transparent group-hover:border-blue-600"}`}><Check className="size-4" /></span></div><p className={`mt-3 text-sm leading-6 ${active ? "text-slate-300" : "text-slate-600"}`}>{item.names}</p><div className={`mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs ${active ? "text-slate-300" : "text-slate-500"}`}><span className="inline-flex items-center gap-1.5"><CalendarDays className="size-3.5" />{item.dates} 2026</span><span className="inline-flex items-center gap-1.5"><MapPin className="size-3.5" />{item.cities}</span></div></button>; })}</div>{!shown.length && <div className="mt-6 border-y border-slate-200 py-12 text-center"><p className="font-semibold">No upcoming crusades match your search.</p></div>}</section>

        <section className="grid gap-8 border-t border-slate-200 py-10 lg:grid-cols-[18rem_minmax(0,1fr)] lg:gap-14"><div><p className="text-sm font-semibold text-blue-700">Final note</p><h2 className="mt-3 text-2xl font-medium">Anything the team should know?</h2></div><div><Field label="Additional information" hint="Optional—share relevant travel experience, availability details, or questions." error={errors.additional_information?.message}><Textarea rows={5} {...register("additional_information")} /></Field><div className="mt-8 flex flex-col-reverse gap-4 border-t border-slate-200 pt-7 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-md text-xs leading-5 text-slate-500">Submitting interest does not confirm travel. Wait for the missions department before making bookings.</p><Button type="submit" disabled={isSubmitting} size="lg" className="rounded-full px-7"><Plane />{isSubmitting ? "Submitting…" : selected.length ? `Submit ${selected.length} crusade choice${selected.length === 1 ? "" : "s"}` : "Submit crusade interest"}</Button></div></div></section>
      </form>
    </main>
  </div>;
}
