import * as React from "react";
import { CircleCheck, Download, FileSpreadsheet, Pencil, RotateCcw, Search, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { Breadcrumbs } from "@/components/ui/breadcrumbs";
import { Button } from "@/components/ui/button";
import { Field } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { deleteJSON, getJSON, patchJSON } from "@/lib/api";

function Filter({ label, value, setValue, options, all }) { return <Field label={label}><Select value={value} onChange={(event) => setValue(event.target.value)}><option value="">{all}</option>{options.map(([key,name]) => <option key={key} value={key}>{name}</option>)}</Select></Field>; }

export function UpcomingCrusadesAdmin() {
  const [data, setData] = React.useState(null);
  const [scheduleQuery, setScheduleQuery] = React.useState("");
  const [updatingCode, setUpdatingCode] = React.useState("");
  const [editingCode, setEditingCode] = React.useState("");
  const [draft, setDraft] = React.useState({ nation: "", names: "", dates: "", cities: "" });
  const [query, setQuery] = React.useState(""); const [zone, setZone] = React.useState(""); const [destination, setDestination] = React.useState(""); const [passport, setPassport] = React.useState(""); const [sort, setSort] = React.useState("created_at:desc");
  const params = React.useMemo(() => { const value = new URLSearchParams(); if (query.trim()) value.set("q", query.trim()); if (zone) value.set("zone", zone); if (destination) value.set("destination", destination); if (passport) value.set("passport", passport); const [field,direction] = sort.split(":"); value.set("sort",field); value.set("direction",direction); return value; }, [query,zone,destination,passport,sort]);
  const load = React.useCallback(() => getJSON(`/upcoming-crusades/admin?${params}`).then(setData).catch((error) => toast.error(error.message)), [params]);
  React.useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [load]);
  async function remove(row) { if (!window.confirm(`Remove ${row.zone_name}'s upcoming crusade interest?`)) return; try { await deleteJSON(`/upcoming-crusades/admin/${row.id}`); await load(); toast.success("Expression of interest removed."); } catch (error) { toast.error(error.message); } }
  async function setAssigned(item) { setUpdatingCode(item.code); try { await patchJSON(`/upcoming-crusades/admin/opportunities/${item.code}`, { assigned: !item.assigned }); await load(); toast.success(item.assigned ? "Crusade is available again." : "Crusade marked as assigned."); } catch (error) { toast.error(error.message); } finally { setUpdatingCode(""); } }
  function startEdit(item) { setEditingCode(item.code); setDraft({ nation: item.nation, names: item.names, dates: item.dates, cities: item.cities }); }
  async function saveEdit(item) { setUpdatingCode(item.code); try { await patchJSON(`/upcoming-crusades/admin/opportunities/${item.code}`, { details: draft }); await load(); setEditingCode(""); toast.success("Crusade details updated."); } catch (error) { toast.error(error.message); } finally { setUpdatingCode(""); } }
  async function removeOpportunity(item) { if (!window.confirm(`Remove ${item.names} in ${item.nation} from the public list?`)) return; setUpdatingCode(item.code); try { await deleteJSON(`/upcoming-crusades/admin/opportunities/${item.code}`); await load(); toast.success("Crusade removed from the public list."); } catch (error) { toast.error(error.message); } finally { setUpdatingCode(""); } }
  async function restoreOpportunity(item) { setUpdatingCode(item.code); try { await patchJSON(`/upcoming-crusades/admin/opportunities/${item.code}`, { removed: false }); await load(); toast.success("Crusade restored to the public list."); } catch (error) { toast.error(error.message); } finally { setUpdatingCode(""); } }
  function exportRows(format) { const value = new URLSearchParams(params); value.set("format", format); window.location.assign(`/api/upcoming-crusades/admin/export?${value}`); }
  const options = data?.filter_options || { zones: [], destinations: [], passports: [] };
  const opportunities = data?.opportunities || [];
  const scheduleShown = opportunities.filter((item) => `${item.nation} ${item.names} ${item.cities} ${item.dates}`.toLowerCase().includes(scheduleQuery.trim().toLowerCase()));
  const assignedCount = opportunities.filter((item) => item.assigned).length;
  const removedCount = opportunities.filter((item) => item.removed).length;
  return <div className="mx-auto max-w-7xl"><Breadcrumbs items={[{ label: "Reports dashboard", to: "/dashboard" }, { label: "Upcoming crusades" }]} /><header className="flex flex-col gap-5 pb-10 pt-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-blue-700">Nations & Continents Edition</p><h2 className="mt-2 text-4xl font-normal tracking-[-0.035em]">Upcoming crusade interests</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Review travel-ready zone representatives by destination, passport, and ministry location.</p></div><div className="flex gap-2"><Button variant="outline" className="rounded-full" onClick={() => exportRows("csv")} disabled={!data?.filtered_total}><Download /> CSV</Button><Button variant="outline" className="rounded-full" onClick={() => exportRows("xlsx")} disabled={!data?.filtered_total}><FileSpreadsheet /> Excel</Button></div></header>
    <section className="mb-12"><div className="bg-[#121944] p-6 text-white sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-2xl"><p className="text-sm font-semibold text-blue-300">Crusade availability</p><h3 className="mt-2 text-2xl font-medium text-white">Manage the published crusade list</h3><p className="mt-3 text-sm leading-6 text-slate-200">Mark a crusade as assigned, edit its details, or remove it from the public form. <strong className="text-white">{assignedCount} assigned</strong> · <strong className="text-white">{removedCount} removed</strong> · {opportunities.length - removedCount} published.</p></div><div className="w-full lg:max-w-sm"><label htmlFor="crusade-manager-search" className="mb-2 block text-sm font-semibold text-white">Find a crusade</label><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-500" /><Input id="crusade-manager-search" value={scheduleQuery} onChange={(event) => setScheduleQuery(event.target.value)} className="border-white bg-white pl-9 text-slate-950 placeholder:text-slate-500" placeholder="Nation, crusade, city or date" /></div></div></div></div>
      <div className="border-x border-b border-slate-200 bg-slate-50 p-3 sm:p-5">{!data ? <Skeleton className="h-32 rounded-none" /> : <div className="grid max-h-[40rem] gap-3 overflow-y-auto pr-1 md:grid-cols-2">{scheduleShown.map((item) => <article key={item.code} className={`border bg-white ${item.removed ? "border-dashed border-slate-300" : item.assigned ? "border-slate-400" : "border-slate-200"}`}><div className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h4 className="font-semibold text-slate-950">{item.nation}</h4>{item.assigned && <span className="rounded-full bg-slate-700 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-white">Assigned</span>}{item.removed && <span className="rounded-full border border-slate-400 bg-white px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-slate-700">Removed</span>}</div><p className="mt-2 text-sm font-medium leading-5 text-slate-800">{item.names}</p></div></div><div className="mt-3 bg-slate-100 px-3 py-2.5 text-xs leading-5 text-slate-700"><strong>{item.dates} 2026</strong><span aria-hidden="true"> · </span>{item.cities}<span aria-hidden="true"> · </span>{item.interest_count} interested</div></div>
        {editingCode === item.code && <div className="border-t border-blue-200 bg-blue-50 p-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="Nation"><Input value={draft.nation} onChange={(event) => setDraft((value) => ({ ...value, nation: event.target.value }))} /></Field><Field label="Crusade name"><Input value={draft.names} onChange={(event) => setDraft((value) => ({ ...value, names: event.target.value }))} /></Field><Field label="Date"><Input value={draft.dates} onChange={(event) => setDraft((value) => ({ ...value, dates: event.target.value }))} placeholder="29 Aug" /></Field><Field label="City"><Input value={draft.cities} onChange={(event) => setDraft((value) => ({ ...value, cities: event.target.value }))} /></Field></div><div className="mt-4 flex justify-end gap-2"><Button type="button" size="sm" variant="ghost" onClick={() => setEditingCode("")}><X /> Cancel</Button><Button type="button" size="sm" disabled={updatingCode === item.code} onClick={() => saveEdit(item)}>{updatingCode === item.code ? "Saving…" : "Save changes"}</Button></div></div>}
        <div className="flex flex-wrap gap-2 border-t border-slate-200 px-4 py-3">{item.removed ? <Button type="button" size="sm" variant="outline" disabled={updatingCode === item.code} onClick={() => restoreOpportunity(item)}><RotateCcw />{updatingCode === item.code ? "Restoring…" : "Restore to list"}</Button> : <><Button type="button" size="sm" variant={item.assigned ? "outline" : "secondary"} disabled={updatingCode === item.code} onClick={() => setAssigned(item)}>{item.assigned ? <RotateCcw /> : <CircleCheck />}{updatingCode === item.code ? "Saving…" : item.assigned ? "Make available" : "Mark assigned"}</Button><Button type="button" size="sm" variant="ghost" disabled={updatingCode === item.code || editingCode === item.code} onClick={() => startEdit(item)}><Pencil /> Edit</Button><Button type="button" size="sm" variant="ghost" className="text-slate-600 hover:text-red-700" disabled={updatingCode === item.code} onClick={() => removeOpportunity(item)}><Trash2 /> Remove from list</Button></>}</div></article>)}</div>}
        {data && !scheduleShown.length && <p className="py-10 text-center text-sm text-slate-600">No crusades match this search.</p>}
      </div>
    </section>
    <section className="border-y border-slate-200 py-6"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-[1.3fr_repeat(4,auto)] xl:items-end"><Field label="Search"><div className="relative"><Search className="absolute left-0 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><Input value={query} onChange={(event) => setQuery(event.target.value)} className="pl-7" placeholder="Name, designation, zone or group" /></div></Field><Filter label="Zone" value={zone} setValue={setZone} options={options.zones.map((name) => [name,name])} all="All zones" /><Filter label="Destination" value={destination} setValue={setDestination} options={options.destinations.map((item) => [item.code,item.name])} all="All destinations" /><Filter label="Passport" value={passport} setValue={setPassport} options={options.passports.map((item) => [item.code,item.name])} all="All passports" /><Field label="Sort"><Select value={sort} onChange={(event) => setSort(event.target.value)}><option value="created_at:desc">Newest first</option><option value="created_at:asc">Oldest first</option><option value="zone:asc">Zone A–Z</option><option value="destination:asc">Destination A–Z</option><option value="name:asc">Name A–Z</option></Select></Field></div></section>
    <div className="flex gap-7 py-6 text-sm"><p><strong className="text-2xl font-medium">{data?.total ?? "—"}</strong><span className="ml-2 text-slate-500">zones interested</span></p><p className="self-center text-slate-500">{data?.filtered_total ?? 0} shown</p></div>
    <div className="border-y border-slate-200">{!data ? <Skeleton className="h-40 rounded-none" /> : data.rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead><tr className="text-left text-xs text-slate-500"><th className="px-3 py-3">Participant</th><th className="px-3 py-3">Destinations</th><th className="px-3 py-3">Passport</th><th className="px-3 py-3">Ministry</th><th className="px-3 py-3">Submitted</th><th className="px-3 py-3">Action</th></tr></thead><tbody>{data.rows.map((row) => <tr key={row.id} className="border-t border-slate-200 align-top"><td className="px-3 py-4"><p className="font-semibold">{row.full_name}</p><p className="mt-1 text-xs text-slate-500">{row.designation}</p><p className="mt-1 text-xs text-slate-500">{row.reference_code}</p></td><td className="max-w-sm px-3 py-4"><div className="space-y-2">{row.opportunities.map((item) => <div key={item.id}><p className="font-semibold">{item.opportunity_nation} · {item.opportunity_names}</p><p className="mt-0.5 text-xs leading-5 text-slate-500">{item.opportunity_dates} · {item.opportunity_cities}</p></div>)}</div></td><td className="px-3 py-4">{row.passport_country_name}</td><td className="px-3 py-4"><p>{row.zone_name}</p><p className="mt-1 text-xs text-slate-500">{row.group_name || "No group selected"}</p></td><td className="whitespace-nowrap px-3 py-4 text-xs text-slate-500">{row.created_at}</td><td className="px-3 py-4"><Button variant="ghost" size="sm" className="text-slate-600 hover:text-red-700" onClick={() => remove(row)}><Trash2 /> Remove</Button></td></tr>)}</tbody></table></div> : <div className="py-16 text-center"><p className="font-semibold">No expressions of interest found</p><p className="mt-2 text-sm text-slate-500">Change the filters or wait for zones to submit.</p></div>}</div>
  </div>;
}
