import * as React from "react";
import { Download, FileSpreadsheet, Search, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Breadcrumbs } from "@/components/ui/breadcrumbs";
import { Button } from "@/components/ui/button";
import { Field } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { deleteJSON, getJSON } from "@/lib/api";

function Filter({ label, value, setValue, options, all }) { return <Field label={label}><Select value={value} onChange={(event) => setValue(event.target.value)}><option value="">{all}</option>{options.map(([key,name]) => <option key={key} value={key}>{name}</option>)}</Select></Field>; }

export function UpcomingCrusadesAdmin() {
  const [data, setData] = React.useState(null);
  const [query, setQuery] = React.useState(""); const [zone, setZone] = React.useState(""); const [destination, setDestination] = React.useState(""); const [passport, setPassport] = React.useState(""); const [sort, setSort] = React.useState("created_at:desc");
  const params = React.useMemo(() => { const value = new URLSearchParams(); if (query.trim()) value.set("q", query.trim()); if (zone) value.set("zone", zone); if (destination) value.set("destination", destination); if (passport) value.set("passport", passport); const [field,direction] = sort.split(":"); value.set("sort",field); value.set("direction",direction); return value; }, [query,zone,destination,passport,sort]);
  const load = React.useCallback(() => getJSON(`/upcoming-crusades/admin?${params}`).then(setData).catch((error) => toast.error(error.message)), [params]);
  React.useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [load]);
  async function remove(row) { if (!window.confirm(`Remove ${row.zone_name}'s upcoming crusade interest?`)) return; try { await deleteJSON(`/upcoming-crusades/admin/${row.id}`); await load(); toast.success("Expression of interest removed."); } catch (error) { toast.error(error.message); } }
  function exportRows(format) { const value = new URLSearchParams(params); value.set("format", format); window.location.assign(`/api/upcoming-crusades/admin/export?${value}`); }
  const options = data?.filter_options || { zones: [], destinations: [], passports: [] };
  return <div className="mx-auto max-w-7xl"><Breadcrumbs items={[{ label: "Reports dashboard", to: "/dashboard" }, { label: "Upcoming crusades" }]} /><header className="flex flex-col gap-5 pb-10 pt-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-blue-700">Nations & Continents Edition</p><h2 className="mt-2 text-4xl font-normal tracking-[-0.035em]">Upcoming crusade interests</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Review travel-ready zone representatives by destination, passport, and ministry location.</p></div><div className="flex gap-2"><Button variant="outline" className="rounded-full" onClick={() => exportRows("csv")} disabled={!data?.filtered_total}><Download /> CSV</Button><Button variant="outline" className="rounded-full" onClick={() => exportRows("xlsx")} disabled={!data?.filtered_total}><FileSpreadsheet /> Excel</Button></div></header>
    <section className="border-y border-slate-200 py-6"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-[1.3fr_repeat(4,auto)] xl:items-end"><Field label="Search"><div className="relative"><Search className="absolute left-0 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><Input value={query} onChange={(event) => setQuery(event.target.value)} className="pl-7" placeholder="Name, designation, zone or group" /></div></Field><Filter label="Zone" value={zone} setValue={setZone} options={options.zones.map((name) => [name,name])} all="All zones" /><Filter label="Destination" value={destination} setValue={setDestination} options={options.destinations.map((item) => [item.code,item.name])} all="All destinations" /><Filter label="Passport" value={passport} setValue={setPassport} options={options.passports.map((item) => [item.code,item.name])} all="All passports" /><Field label="Sort"><Select value={sort} onChange={(event) => setSort(event.target.value)}><option value="created_at:desc">Newest first</option><option value="created_at:asc">Oldest first</option><option value="zone:asc">Zone A–Z</option><option value="destination:asc">Destination A–Z</option><option value="name:asc">Name A–Z</option></Select></Field></div></section>
    <div className="flex gap-7 py-6 text-sm"><p><strong className="text-2xl font-medium">{data?.total ?? "—"}</strong><span className="ml-2 text-slate-500">zones interested</span></p><p className="self-center text-slate-500">{data?.filtered_total ?? 0} shown</p></div>
    <div className="border-y border-slate-200">{!data ? <Skeleton className="h-40 rounded-none" /> : data.rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead><tr className="text-left text-xs text-slate-500"><th className="px-3 py-3">Participant</th><th className="px-3 py-3">Destination</th><th className="px-3 py-3">Passport</th><th className="px-3 py-3">Ministry</th><th className="px-3 py-3">Submitted</th><th className="px-3 py-3">Action</th></tr></thead><tbody>{data.rows.map((row) => <tr key={row.id} className="border-t border-slate-200 align-top"><td className="px-3 py-4"><p className="font-semibold">{row.full_name}</p><p className="mt-1 text-xs text-slate-500">{row.designation}</p><p className="mt-1 text-xs text-slate-500">{row.reference_code}</p></td><td className="max-w-xs px-3 py-4"><p className="font-semibold">{row.opportunity_nation}</p><p className="mt-1 text-xs leading-5 text-slate-500">{row.opportunity_dates} · {row.opportunity_cities}</p></td><td className="px-3 py-4">{row.passport_country_name}</td><td className="px-3 py-4"><p>{row.zone_name}</p><p className="mt-1 text-xs text-slate-500">{row.group_name || "No group selected"}</p></td><td className="whitespace-nowrap px-3 py-4 text-xs text-slate-500">{row.created_at}</td><td className="px-3 py-4"><Button variant="ghost" size="sm" className="text-slate-600 hover:text-red-700" onClick={() => remove(row)}><Trash2 /> Remove</Button></td></tr>)}</tbody></table></div> : <div className="py-16 text-center"><p className="font-semibold">No expressions of interest found</p><p className="mt-2 text-sm text-slate-500">Change the filters or wait for zones to submit.</p></div>}</div>
  </div>;
}
